INSERT_LOCAL_URL = "INSERT INTO local_url(url,global_url_id) VALUES (%s, %s)"
CHECK_LOCAL_URL = "SELECT id FROM local_url WHERE url = %s AND global_url_id = %s"

INSERT_CLUSTER = "INSERT INTO cluster(cluster_name) VALUES (%s)"
CHECK_CLUSTER = "SELECT id FROM cluster WHERE cluster_name = %s"

INSERT_AUTHORS = ("INSERT INTO authors(main_name, block_name, website, contact, about, orcid_id) "
                              "VALUES (%(parsed_name)s,%(block_name)s,%(website)s,%(contact)s,%(about)s,%(orcid_id)s)")
COUNT_AUTHORS = "SELECT COUNT(*) FROM authors WHERE block_name = %s"
CHECK_AUTHORS = "SELECT id FROM authors WHERE block_name = %s"


COUNT_MATCH_AUTHOR_BY_ALIAS = ("SELECT COUNT(*)"
                               "FROM name_alias, authors "
                               "WHERE authors.id = name_alias.authors_id "
                               "AND authors.block_name = %s "
                               "AND alias= %s")
MATCH_AUTHOR_BY_ALIAS = ("SELECT authors.id "
                         "FROM name_alias, authors "
                         "WHERE authors.id = name_alias.authors_id "
                         "AND authors.block_name = %s "
                         "AND alias= %s")


INSERT_ALIAS = "INSERT IGNORE INTO name_alias(authors_id, alias) VALUES (%s, %s)"
SELECT_ALIAS = "SELECT id FROM name_alias WHERE authors_id = %s AND alias = %s INTO @id"
INSERT_ALIAS_SOURCE = "INSERT IGNORE INTO alias_source(alias_id,url_id) VALUES (@id,%s)"


INSERT_PUBLICATION_AUTHORS = ("INSERT INTO publication_authors(url_id, author_id, priority) VALUES (%s, %s, %s)")

INSERT_PUBLICATION=   ("INSERT INTO publication"
                       "       (url_id,"
                       "        cluster_id,"
                       "        differences,"
                       "        title,"
                       "        pages, "
                       "        note,"
                       "        doi,"
                       "        abstract,"
                       "        copyright,"
                       "        date_added,"
                       "        date_published,"
                       "        volume,"
                       "        number)"
                       "VALUES (%(url_id)s, "
                       "        %(cluster_id)s,"
                       "        %(differences)s,"
                       "        %(title)s,"
                       "        %(pages)s, "
                       "        %(note)s,"
                       "        %(doi)s,"
                       "        %(abstract)s,"
                       "        %(copyright)s,"
                       "        %(date_added)s,"
                       "        %(date_published)s,"
                       "        %(volume)s,"
                       "        %(number)s"
                       "       )")


INSERT_DEFAULT_TABLE= ("INSERT INTO default_table"
                       "       (type_id, "
                       "        study_field_id,"
                       "        url_id,"
                       "        title,"
                       "        pages_from, "
                       "        pages_to,"
                       "        series,"
                       "        edition,"
                       "        note,"
                       "        location,"
                       "        publisher,"
                       "        institution,"
                       "        school,"
                       "        address,"
                       "        isbn,"
                       "        doi,"
                       "        howpublished,"
                       "        abstract,"
                       "        copyright,"
                       "        date_added,"
                       "        date_published,"
                       "        book_title,"
                       "        journal,"
                       "        volume,"
                       "        number)"
                       "VALUES (%(type_id)s, "
                       "        %(study_field_id)s,"
                       "        %(url_id)s,"
                       "        %(title)s,"
                       "        %(pages_from)s, "
                       "        %(pages_to)s,"
                       "        %(series)s,"
                       "        %(edition)s,"
                       "        %(note)s,"
                       "        %(location)s,"
                       "        %(publisher)s,"
                       "        %(institution)s,"
                       "        %(school)s,"
                       "        %(address)s,"
                       "        %(isbn)s,"
                       "        %(doi)s,"
                       "        %(howpublished)s,"
                       "        %(abstract)s,"
                       "        %(copyright)s,"
                       "        %(date_added)s,"
                       "        %(date_published)s,"
                       "        %(book_title)s,"
                       "        %(journal)s,"
                       "        %(volume)s,"
                       "        %(number)s"
                       "       )")
